# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerShell
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Windows Terminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub CLI
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHubCopilotCLI
      directives:
        description: Install GitHub Copilot CLI
        allowPrerelease: true
      settings:
        id: GitHub.Copilot
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - PowerShell
      id: Oh My Posh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NVM
      directives:
        description: Install NVM for Windows
        allowPrerelease: true
      settings:
        id: CoreyButler.NVMforWindows
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: kubectl
      directives:
        description: Install kubectl
        allowPrerelease: true
      settings:
        id: Kubernetes.kubectl
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OpenLens
      directives:
        description: Install OpenLens
        allowPrerelease: true
      settings:
        id: MuhammedKalkan.OpenLens
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: k9s
      directives:
        description: Install k9s
        allowPrerelease: true
      settings:
        id: Derailed.k9s
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Chrome
      directives:
        description: Install Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget

  configurationVersion: 0.2.0
